config/routes.rb
Rails.application.routes.draw do
  resources :posts
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  scope :not_hidden, -> { where(hidden: false) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(hidden: :desc, updated_at: :desc)
    @post = Post.new
    render layout: "door"
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    render layout: "door"
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { rendirect_to root_path }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:body, :name, :email, :url)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% unless current_user %>
  <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
<% else %>
  <%= current_user[:name] %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Theses" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Theses" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/door.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Nail Your Theses!" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "500 years ago, Martin Luther nailed 95 theses to the door of a German church, kicking off the Protestant Reformation. What are your theses? What do you have to say to the contemporary world?" %>">
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Nail Your Theses!" />
  <meta property="og:description"   content="<%= content_for?(:description) ? yield(:description) : "500 years ago, Martin Luther nailed 95 theses to the door of a German church, kicking off the Protestant Reformation. What are your theses? What do you have to say to the contemporary world?" %>" />
  <meta property="og:image"         content="http://www.nail-your-theses.com<%= asset_path('nail-your-theses.jpg') %>" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body class="door">
  <p id="notice"><%= notice %></p>

  <%= yield %>

  <br /><br /><br /><br /><br />

  <p style="text-align:center; color:white; font-size: 2rem;">A project of <a href="http://micahredding.com">Micah Redding</a> and John Mark. See why <strong><a href="http://micahredding.com/blog/christian-transhumanism-is-the-next-reformation">Christian Transhumanism is the Next Reformation</a></strong>.</p>

  <br /><br /><br /><br /><br />


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=1946807255535850';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, placeholder: "Your thesis", style: "width: 100%", rows: 3, required: true %>
  </div>

  <div class="field">
    <%= f.text_field :name, placeholder: "Your Name", required: true %>
    <%= f.text_field :email, placeholder: "Email", type:'email', required: true %>
  </div>

  <div class="field">
    <%= f.text_field :url, placeholder: "http://www.YourWebsite.com" %>
  </div>

  <div class="actions">
    <%= f.submit "Nail it!" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article>
  <p class="content"><%= post.body %></p>
  <p class="author">— <%= link_to post.name, post.url %></p>

  <div class="fb-share-button" data-href="<%= post_url(post) %>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%= post_url(post) %>">Share</a></div>      

</article>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Nail Your Theses!</h1>

<article>
  <%= render 'form', post: @post %>
</article>

<% @posts.each do |post| %>
  <%= render :partial => 'post', :locals => {:post => post} %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% content_for :description do %><%= @post.body %><% end %>

<h1><a href="/">Nail Your Theses</a></h1>

<%= render :partial => 'post', :locals => {:post => @post} %>

<br />
<p style="text-align:center; font-size: 2rem;"><a href="/" style="color:white;"><strong>Now, add your own!</strong></a></p>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />